language: elixir
elixir:
- 1.5.1
otp_release:
- 20.0
deploy:
  provider: heroku
  api_key:
    secure: DNq+OJaVI34E1upFoPZrQcrsJVZwf6/lg+6fp0qxLvMkYntP3MVT0n6Oj0d78U0U3eL/mgzk0yTjUBboT9gFzVMygPdwwm7GRoJ9rkz883AOKxzsE/NFXqBJjAZGL97a+zPC3oOE+QwmkqPxsUIrOViYs+eVouJJd6flvW+2H0J6O2Dnnx0bhTDYgPaE0cTFYVNKCcnIThQ/IGbyL6L5b1rIt0zU/Hg4w6h4686SawX/5HysnLZka+Mnha3e/6yE9Xh5nlbREgRgQmw76P/EREo/VIcCWgR1T2QFYbm3bmIQvMhlB6vY94DWefEvB+sHo2x5lNqOsn3hnKWPe9JJSW4i3MXzjRu2ZCOWh9Q8p8x1tVqaQBvhyPj/gD5WBxLMimuNANVrc8XfAMumqEZDmtbOg8RVCwC7LqEv2Zi8nBa5Zo6L1BWq409FBlsMrG0/QcYUd2JdYbZGqFjJbZH4jsTrbVdMK+O+JA914IIwbtlg+Ghzeq6WpfhrZzSO9xMSPZECraZCmQIH+nOKvhks/mTgTmqOuwKq8hY9darZYwgcdgzcHW9C7WEGc6mXyBEaLCW+7w0/WrAFXmrKgxtYRV+KNWTYTqlBN78ExHHMA3M/X63+lLMYIFF0aZDyOonpDib+drLgesxpYc1SPQxjc1KuLrX3ycjvmHQHsSbzQXI=
  app: glacial-stream-28693
  on:
    repo: radu/platform
